### ISSUE TITLE
Halo65 not supported

### ISSUE THREAD

**Issue by tiicker** [donn/nudelta#69] opened 2024-01-12 21:59 UTC
### Version

0.7.4

### Operating System

Getting error saying Nuphy Halo65 is not a supported keyboard. 

### Description

Getting error saying Nuphy Halo65 is not a supported keyboard.

**Comment by donn** [comment] 2024-01-13 00:41
Duplicate of #16

**Closed by donn** 2024-01-13 00:41 UTC
